name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo build test by @houssk
    - name: Run a multi-line script
      run: 
        npm install
        npm run test
